# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodyapp', '0005_orderdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={},
        ),
    ]
