# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodyapp', '0006_auto_20171025_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order Details'},
        ),
    ]
