# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodyapp', '0009_order_orderdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name_plural': 'Order Details'},
        ),
    ]
