# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodyapp', '0010_auto_20171101_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodyapp.Driver'),
        ),
    ]
